services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: mikrotik-app
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: ${APP_ENV:-production}
      APP_DEBUG: ${APP_DEBUG:-false}
      DB_CONNECTION: mysql
      DB_HOST: ${DB_HOST:-mysql}
      DB_PORT: ${DB_PORT:-3306}
      DB_DATABASE: ${DB_DATABASE:-mikrotikman}
      DB_USERNAME: ${DB_USERNAME:-root}
      DB_PASSWORD: ${DB_PASSWORD:-@Terbuka32100}
    networks:
      - shared

networks:
  shared:
    external: true
